#!/bin/sh

if ! ps -ef | grep "aseqnet rpi-wired" | grep -v grep > /dev/null
then
    echo Starting aseqnet
    chrt 5 aseqnet rpi-wired &
fi
if ! ps -ef | grep fluidsynth | grep -v grep > /dev/null
then
    echo Starting fluidsynth
    # -K <num midi channels> 5 is out of range??
    # -g <master gain:0-10, default 0.2>
    chrt 4 /usr/bin/fluidsynth -a alsa -m alsa_seq -g 5 -i -s /usr/share/sounds/sf2/FluidR3_GM.sf2 &
fi
